# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import magic.core.models.fields
import magic.core.models.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('_types', models.CharField(max_length=1024)),
                ('type_line', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('collector_number', models.CharField(blank=True, max_length=64, null=True)),
                ('mana_cost', magic.core.models.fields.ManaField(blank=True, default='', max_length=32, null=True)),
                ('power', models.IntegerField(default=0)),
                ('toughness', models.IntegerField(default=0)),
            ],
            bases=(models.Model, magic.core.models.types.CardTypes),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cards', models.ManyToManyField(related_name='deck', to='core.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.IntegerField(default=20)),
                ('poison_counters', models.IntegerField(default=0)),
                ('mana_pool', magic.core.models.fields.ManaField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
