# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20170917_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="_subtypes",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
