# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:15
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_groups(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    Deck = apps.get_model('core', 'Deck')
    Player = apps.get_model('core', 'Player')
    player_group, created = Group.objects.get_or_create(name='player')

    # add deck permissions
    deck_content_type = ContentType.objects.get_for_model(Deck)
    for p in Permission.objects.filter(content_type=deck_content_type):
        player_group.permissions.add(p)

    # add player permissions
    player_content_type = ContentType.objects.get_for_model(Player)
    for p in Permission.objects.filter(content_type=player_content_type):
        player_group.permissions.add(p)
    player_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171004_1058'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
