# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_permission_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='core.Set'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='deck', to='core.Card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Set'),
        ),
    ]
